name: Build Docs Site

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'scripts/build-docs.ps1'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build docs with MkDocs
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material
          python -m mkdocs build --site-dir site
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: site
